Works section and about myself PR
laurianerzb/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-09-22 19:06 UTC by laurianerzb

#Portfolio: finish mobile version
#Work section and about myself PR

#Added to index.html the work and about myself section
#Added to styles.css styles related to work and about myself section
#Checking of linters errors

2022-09-22 20:05 UTC, BertrandConxy requested changes
Hi @laurianerzb , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- good use of comments
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 20:05 UTC, BertrandConxy commented on index.html
> +                            </div>
- [ ] This section is structured in a tricky way because you are expected to implement `nested lists`.  The technology categories(like languages, framework, etc) should be in the list and the technologies in each category are supposed to be in the list too. If you don't have an idea on how to do it, here is [an article](https://www.webucator.com/article/how-to-properly-nest-lists-in-html/) that will help you get the point 😉

2022-09-22 20:05 UTC, BertrandConxy commented on styles.css
> +  margin-bottom: 2px;
- [ ] Please add the correct styles to this section. You can see what to improve based on the comparison below 👇 
Figma
![image](https://user-images.githubusercontent.com/90222110/191840591-1591f98d-7626-4bf8-ba4c-885dbd043371.png)

Your design
![image](https://user-images.githubusercontent.com/90222110/191840409-12718ae6-c07e-4fd9-a5ec-35f58cd51189.png)

2022-09-23 00:39 UTC, mgmediaweb commented on index.html
> +                  <li> <a id="profile-link" href="https://angellist.com/" target="_blank"> <i class="fa fa-angellist"></i></a> </li>
Kindly, this correction is not yet reflected in your project, I suggest you make it

2022-09-23 00:42 UTC, mgmediaweb commented on index.html
> +                <div class="project-work">
Good job following the advice of the previous reviewer

2022-09-23 01:12 UTC, mgmediaweb requested changes
Hi @laurianerzb , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost3](https://user-images.githubusercontent.com/41912912/191874432-7dc1df17-be0b-469b-a8aa-c672d8b63235.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️

Kindly check the comments on the image to make your site look more like the original figma design.
![image](https://user-images.githubusercontent.com/41912912/191874473-07af4f53-44ab-4841-b1c4-59f8c8e99c38.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 02:49 UTC, franclobo approved these changes
Hi @laurianerzb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 


## Optional suggestions

- [ ] **[OPTIONAL]** To fix the LICENSE link in your README file we could use `[MIT](./MIT.md)` instead of `[MIT](./LICENSE)` it depends of the file's name. Kindly add the LICENSE section in your README file.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 06:58 UTC, merged