Desktop version PR
laurianerzb/Portfolio-setup-and-mobile-first pull request #5
Opened 2022-09-29 14:00 UTC by laurianerzb

### Desktop version PR

#Added desktop nav inside html file
#Added media queries for desktop inside css
#linters errors Checked

2022-09-29 14:55 UTC, Abenezer-Tilahun requested changes
Hi @laurianerzb   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional   README
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 14:55 UTC, Abenezer-Tilahun commented on styles.css
> +@media (min-width: 764px) {
- [ ] As requested in the requirements, please adjust your media query to 768px for the best responsiveness on all mobile devices. 😀
![az](https://user-images.githubusercontent.com/93598189/193057978-0225cdce-dac2-43f8-ab8f-5ef0cf03b2cf.png)

2022-09-29 14:55 UTC, Abenezer-Tilahun commented on styles.css
> +}
- [ ] You must replicate the design as much as possible (e.g., font, colors, images, text, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Your design For desktop size Look likes this : For contact section 
![Capture](https://user-images.githubusercontent.com/93598189/193060403-803089bb-f0f0-4516-b010-e2c612e4386a.PNG)

The Figma design For contact section Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/193060685-07f67a5b-b757-4229-b86a-1d42b16260e1.PNG)

- [ ] Kindly work on the contact section alignment for desktop size and adjust the position of "Get In Touch" button .

- [ Optional ] Kindly adjust the background color of "Headline" and "About Section" to white just like the figma design.

- [ ] The Minimum mobile screen size should be 375px. For making mobile screen size responsive for contact section, I recommend you to adjust it just like the figma design .

Your Contact section at the Minimum mobile screen size 375px : 
![Capture](https://user-images.githubusercontent.com/93598189/193064504-47acf974-d99e-4e86-a79c-4d51d4a361fa.PNG)

The Figma design at 375px
![Capture](https://user-images.githubusercontent.com/93598189/193064857-8fb504ac-4c47-44c6-b79f-5b3697be10c4.PNG)

2022-09-29 17:22 UTC, levy002 requested changes
## Hello @laurianerzb   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer kindly make sure you `CONTACT SECTION`  is not affected, it still matches the provided Figma design. :wink: 

    - ### Your design

    ![image](https://user-images.githubusercontent.com/87197412/193100086-e5910b76-686e-49db-ae82-244c132ce2ed.png)

    - ### Figma design
    ![image](https://user-images.githubusercontent.com/87197412/193100262-f0de3895-d7a8-44c1-95b0-176d217e25c4.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 00:40 UTC, mgmediaweb requested changes
Hi @laurianerzb, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost4](https://user-images.githubusercontent.com/41912912/193165672-08925d58-6bee-4818-aff9-e1159d5ec80c.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️

Kindly, I suggest you compare very well the original design of Figma with yours, I found these details to make your page look better
![image](https://user-images.githubusercontent.com/41912912/193165590-460a5cd5-e8b3-4aad-94fe-023497d0c6a9.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 01:10 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @laurianerzb , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 06:58 UTC, merged