Mobile menu PR
laurianerzb/Portfolio-setup-and-mobile-first pull request #9
Opened 2022-10-10 13:34 UTC by laurianerzb

### Mobile menu PR

- Modified index.html
- Modified styles.css
- Added script.js
- Setup linters for html+css+js

2022-10-10 20:49 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey Team(@laurianerzb, @belalgamal46) :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Linters
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-10 20:49 UTC, HAMMAS-SALEEM commented on index.html
> +          </div>
### Your Design
![image](https://user-images.githubusercontent.com/93039359/194948703-5a63a29b-148e-49d8-818d-9f78b65c52ac.png)

### Figma Design
![image](https://user-images.githubusercontent.com/93039359/194948871-fb24ec1a-4058-4dbc-ba34-c7f0665cb197.png)

- [ ] You can see that in the Figma template the close icon is a little bit higher than menu links **(Portfolio, About, Contact)** Kindly make your close icon a little bit higher from the current position :blush:
- [ ] Your menu links **(Portfolio, About, Contact)** are not working on the mobile version. Kindly fix them :+1:
- [ ] You don't have a blur in your design as you can see in the Figma template there is a blur. Kindly fix that :+1:

2022-10-10 22:32 UTC, BenMukebo requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository have been set up correctly. ✔️  
- Good commit history ✔️ 
-  When the user clicks the hamburger button, the mobile menu appears.✔️ 
- When the user clicks the close (X) button, the mobile menu disappears.✔️ 
- When the user clicks any of the mobile menu options, a correct part is displayed and the mobile menu disappears 👏🏻 
- You have followed  JavaScript best practices. ✔️ 
👍  Good job!

 ## Required Changes ♻️
_Check the comments under the review._


You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL ] Please let's make sure that contributions to a group project are distributed equally among the members (commit messages should be fairly equal).


- [ OPTIONAL] Your README looks great 👍🏻, However, it will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd repo name` etc

- [OPTIONAL] This is a group project. Please let's include all the authors in the README file. This makes the README file professional and descriptive. 👨🏻‍🎨

- [OPTIONAL] I would also recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-10 22:32 UTC, BenMukebo commented on script.js
> +});
- [ ] When I click on any of the mobile menu options, the correct part is displayed and the mobile menu disappears  👏🏻 👍🏻 However, the home page still has a blur effect as shown on the image below 👇🏻 Kindly make sure to remove the blur effect on the home page when a user clicks any of the mobile menu options 👍🏻 


![Screenshot from 2022-10-11 00-12-03](https://user-images.githubusercontent.com/79058364/194960802-29f2e14b-abdb-4cfc-9b9a-89477e0334c0.png)
- [OPTIONAL] What about preventing the sub-background from scrolling when the navbar is open? You can use a CSS property `over-flow: hidden;` to do that, which will make your mobile menu correspond to the original design.💯 🥇 

-  Adding these features will make your design look great and look exactly like the Figma design, I highly recommend you do this in the meantime, I'll approve this project since the previous reviewer is skipping this.

2022-10-11 00:01 UTC, levy002 approved these changes
## Hello @laurianerzb :wave: 
### I'm Levy, your PR reviewer
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 07:05 UTC, merged